# Generated by Django 4.0.2 on 2023-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
