# Generated by Django 4.0.2 on 2023-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_name_userlogin_first_name_userlogin_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
