# Generated by Django 4.0.2 on 2023-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_post_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
